# Generated by Django 3.0.8 on 2020-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Biography',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'technologies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('preview_link', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq_questions')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('technologies', models.ManyToManyField(to='portfolio_app.Technologies')),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
